http:
  basePath: "/api/v1/*"
  host: "0.0.0.0"
  port: "8081"
  consolePath: "/console/*"
  
api:
  discovery:
    id: ""

#----Common Block---No change Needed----           
cloudhub:
  username: ""
  password: ""
  
smtp:
  host: ""
  port: ""
  user: ""
  password: ""
  subject: "AVEVA API Exception"
#----Common Block---No change Needed----

db:
 audit: 
  config:
   host: "mastek-db-service.database.windows.net"
   port: "1433"
   user: "![zyhAtvykYzLluT/msxeadEffkC2eJ4BLJ4vTlWLugFw=]"
   password: "![6WuGjnUC9I3aTskMvhD/Lg==]"
   database: "MASTEK-DB"    