#%RAML 1.0 NamedExample
    customer-address: ""
    address: ""
    address-line-2: ""
    address-line-3?: ""
    address-line-4?: ""
    city?: "London"
    state?: ""
    postal-code?: ""
    country?: "UK"